[server]
address = "0.0.0.0"
port = 8080
enableCORS = false
enableXsrfProtection = false
headless = true
fileWatcherType = "none"
maxUploadSize = 50

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[runner]
fastReruns = true
magicEnabled = false

[logger]
level = "info"
