[server]
enableCORS = false
enableXsrfProtection = false
headless = true
fileWatcherType = "none"
maxUploadSize = 50

[browser]
gatherUsageStats = false

[runner]
fastReruns = true
magicEnabled = false

[logger]
level = "info"
